# WARNING: the mesh configuration is currently unsupported!

Main:
    include_config_files: ["pi_config.yml"]

EventSinks:
    RelayEventSink:
      class: "relay_event_sink.RelayEventSink"
      relay_port: 3868
      scan_interval: 5 # every hour
      refresh_socket_conns: 600 # every 10 min

Applications:
    MeshRelayedEventReceiver:
      class: "mesh_relayed_event_receiver.MeshRelayedEventReceiver"

Networks:
    NetworkManager:
      class: "scale_network_manager.ScaleNetworkManager"
      batman_interface: "wlan0:avahi"
      batman_originators_file: "/sys/kernel/debug/batman_adv/bat0/originators"
