# This is our default MQTT configuration for uploading sensed events to our broker.
# Include this file in your other configs to use this default, or you can manually configure your own broker.

EventSinks:
    MQTTEventSink:
      class: "mqtt_event_sink.MQTTEventSink"
      #hostname: "iqueue.ics.uci.edu"
      hostname: "53830014e96a4b8992bbbff1c85161c8.s2.eu.hivemq.cloud"
      # This is no longer registered; was from original SCALE deployment and demo
      #hostname: "dime.smartamerica.io"
      # Assuming this still works, it's a good test broker
      #hostname: "m2m.eclipse.org"
      hostport: 8883
      username: temp
      password: 12345678
      keepalive: 60

# This VirtualSensor will subscribe to ALL event topics; hence you should receive back all events that are
# created locally and sunk via the above MqttSink
Sensors:
    #MqttSensor:
      #class: "network.mqtt_sensor.MqttSensor"
      #hostname: "169.234.25.41"
      #hostport: 1883
      #username: null
      #password: null
      #keepalive: 60
      #mqtt_subscriptions: ["#"]
